<a href="https://colab.research.google.com/github/pandeygargi847-ai/AI-ML-INTERNSHIP-/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
array = np.array((10,20,30,40,50))
print(array)

[10 20 30 40 50]


In [4]:
array = np.array([[10,20,30],
                  [60,40,50]])
print(array)

[[10 20 30]
 [60 40 50]]


In [6]:
array = np.array([[10,20], [30,40],
                  [50,60],[70,80]])
print(array)

[[10 20]
 [30 40]
 [50 60]
 [70 80]]


In [7]:
print(array.ndim) #numpy array returns the number of dimensions of the array

2


In [11]:
print(array.shape)

print(array.size)
print(array.dtype)

(4, 2)
8
int64


In [12]:
print(array[2])

[50 60]


In [14]:
print(array[1,1])

40


In [15]:
array = np.array([[10,20,30],
                  [60,40,60]])
print(array)

[[10 20 30]
 [60 40 60]]


In [17]:
print(array[1,1])

40


In [18]:
print(array[1:3])

[[60 40 60]]


In [25]:
array1 = np.array([10,20,30,40,50])
array2 = np.array([10,20,30,40,50])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2) # to find the exponential form
print(np.sqrt(array1)) #to find the sr root
print(np.power(array1,3)) #for n exponent
print(np.power(a,2)) # for n exponent


[ 20  40  60  80 100]
[0 0 0 0 0]
[ 100  400  900 1600 2500]
[1. 1. 1. 1. 1.]
[         10000000000 -2101438300051996672  2565992168703393792
                    0 -6646187150092009472]
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
[  1000   8000  27000  64000 125000]


In [27]:
arr = np.array([10,20,30,40,50])
print(np.mean(arr))
print()
#defining an array

30.0


In [30]:
# Calculate variance
variance = np.var(arr)
print(f"Variance of arr: {variance}")

Variance of arr: 200.0


In [31]:
# Calculate standard deviation
std_dev = np.std(arr)
print(f"Standard deviation of arr: {std_dev}")

Standard deviation of arr: 14.142135623730951


Notice that the standard deviation (`std_dev`) is the square root of the variance (`variance`).

In [28]:
print(np.max(arr))

50


In [29]:
print(np.min(arr))

10


In [ ]:
print(np.sum(arr)) #

In [33]:
arr = np.array([1,2,3,4,5,6])
print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [34]:
arr = np.array([1,2,3,4,5,6])
print(arr.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [35]:
arr = np.array([1,2,3,4,5,6])
print(arr.reshape(6,1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [39]:
arr = np.array([[1,2],[3,4]])
print(arr.flatten())

[1 2 3 4]


In [40]:
arr = np.array([[1,2,3],
                [4,5,6]])
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [42]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [44]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [46]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [48]:
np.arange(1,11) # array in particular range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
np.random.rand(5) #give random numbers below 1

array([0.32769932, 0.37725956, 0.9790071 , 0.84180517, 0.65733328])

In [50]:
np.random.randint(1,100,10) # give random integers


array([94, 10, 98, 83,  9, 62, 49,  8, 54, 88])

In [ ]:
arr = np.array([1,2,3,4,5,6])
print(np.where(arr == 4))